FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Kalematie

This is an authenticated API which uses 
[Client Credentials Grant](http://tools.ietf.org/html/rfc6749#section-4.4 "Client Credentials Grant") 
flow of the [OAuth2](http://tools.ietf.org/html/rfc6749 "OAuth2") specification as the authentication mechanism.

To use this API:

+   An application encodes its consumer key and secret into a specially encoded set of credentials.
+   An application makes a request to the POST /api/token endpoint to exchange these credentials for a bearer token.
+   When accessing the REST API, the application uses the bearer token to authenticate.

![Authentication flow](http://upload.wikimedia.org/wikipedia/commons/7/71/Authentication_flow_for_the_Sent.ly_Plus_API.png)

About Client Credentials Grant authorization
=======================
Tokens are passwords
--------------------
Keep in mind that the consumer key & secret, bearer token credentials, and the bearer token itself grant access to make requests on behalf of an application. These values should be considered as sensitive as passwords and must not be shared or distributed to untrusted parties.

SSL absolutely required
-----------------------
This manner of authentication is only secure if SSL is used. Therefore, all requests (both to obtain and use the tokens) m  ust use HTTPS endpoints, which is also a requirement of using API v1.0.

Issuing authenticated requests
================================
Step 1: Encode consumer key and secret
--------------------------------------
The steps to encode an application's consumer key and secret into a set of credentials to obtain a bearer token are:

1.  URL encode the consumer key and the consumer secret according to [RFC 1738](http://www.ietf.org/rfc/rfc1738.txt "RFC 1738").
Note that at the time of writing, this will not actually change the consumer key and secret, but this step should still be performed in case the format of those values changes in the future.

2.  Concatenate the encoded consumer key, a colon character ":", and the encoded consumer secret into a single string.

3.  [Base64 encode](http://en.wikipedia.org/wiki/Base64) the string from the previous step.

Below are example values showing the result of this algorithm. Note that the consumer secret used in this page has been disabled and will not work for real requests.

<table>
    <tr>
        <td>Consumer Key</td>
        <td>M2E5MDdjMmYtZWM1NC00YmRlLTlkY1ItZjE3M2ZmMjY5MTA0</td>
    </tr>
    <tr>
        <td>Consumer Secret</td>
        <td>NGU1Nzg5Y2UtYTYxNy01MDM2LWJiYWYtYzE4Y2I5ZGY2MTcx</td>
    </tr>
    <tr>
        <td>RFC 1738 encoded consumer key<br/>(does not change)</td>
        <td>M2E5MDdjMmYtZWM1NC00YmRlLTlkY1ItZjE3M2ZmMjY5MTA0</td>
    </tr>
    <tr>
        <td>RFC 1738 encoded consumer secret<br/>(does not change)</td>
        <td>NGU1Nzg5Y2UtYTYxNy01MDM2LWJiYWYtYzE4Y2I5ZGY2MTcx</td>
    </tr>
    <tr>
        <td>Bearer token credentials</td>
        <td><b>M2E5MDdjMmYtZWM1NC00YmRlLTlkY1ItZjE3M2ZmMjY5MTA0</b>:NGU1Nzg5Y2UtYTYxNy01MDM2LWJiYWYtYzE4Y2I5ZGY2MTcx</td>
    </tr>
    <tr>
        <td>Base64 encoded bearer token credentials</td>
        <td>TTJFNU1EZGpNbVl0WldNMU5DMDBZbVJsTFRsa1kxSXRaakUzTTJabU1qWTVNVEEwOk<br/>5HVTFOemc1WTJVdFlUWXhOeTAxTURNMkxXSmlZV1l0WXpFNFkySTVaR1kyTVRjeA==</td>
    </tr>
</table>

Step 2: Obtain a bearer token
-----------------------------

The value calculated in step 1 must be exchanged for a bearer token by issuing a request to POST api/token:

-   The request must be a <code>HTTP POST</code> request.
-   The request must include an <code>Authorization</code> header with the value of<br/>
   <code>Basic &lt;base64 encoded value from step 1&gt;.</code>
-   The request must include a <code>Content-Type</code> header with the value of<br/>
<code>application/x-www-form-urlencoded;charset=UTF-8</code>.
-   The body of the request must be <code>grant\_type=client\_credentials</code>.

**Example request (Authorization header has been wrapped):**

    POST /api/token HTTP/1.1
    Host: kalematie.cu
    User-Agent: Kalematie Mobile App
    Authorization: Basic TTJFNU1EZGpNbVl0WldNMU5DMDBZbVJsTFRsa1kxSXRaakUzTTJabU1qWTVNVEEwOk
                         5HVTFOemc1WTJVdFlUWXhOeTAxTURNMkxXSmlZV1l0WXpFNFkySTVaR1kyTVRjeA==
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8
    Content-Length: 29
    Accept-Encoding: gzip
    
    grant_type=client_credentials
If the request was formatted correctly, the server will respond with a JSON-encoded payload:


**Example response (access_token has been wrapped):**

    HTTP/1.1 200 OK
    Status: 200 OK
    Content-Type: application/json; charset=utf-8
    ...
    Content-Encoding: gzip
    Content-Length: 140
    
    {"token_type":"bearer","access_token":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%2FAAAAAAAAAAAA
                                           AAAAAAAA%3DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}

Applications should verify that the value associated with the <code>token\_type</code> key of the returned object is <code>bearer</code>. The value associated with the access_token key is the bearer token.

Note that one bearer token is valid for an application at a time. Issuing another request with the same credentials to /api/token will return the same token until it is invalidated.

Step 3: Authenticate API requests with the bearer token
-------------------------------------------------------
The bearer token may be used to issue requests to the REST API endpoints. 

To use the bearer token, construct a normal HTTPS request and include an <code>Authorization</code> header with the value of 

<code>Bearer &lt;base64 access_token value from step 2 response&gt;</code> . Signing is not required.


**Example request (Authorization header has been wrapped):**

    GET /api/list HTTP/1.1
    Host: kalematie.cu
    User-Agent: Kalematie Mobile App
    Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%2FAAAAAAAAAAAA
                          AAAAAAAA%3DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    Accept-Encoding: gzip

**Example response**
    
    HTTP/1.1 200 OK
    Status: 200 OK
    Content-Type: application/json; charset=utf-8
    ...
    Content-Encoding: gzip
    
    {"errorMessage":"","errorCode":0, "responseData":"<json response from API>"}

The values associated with the <code>errorMessage</code> key and the <code>errorCode</code> key of the returned
object may be used to see if an error occurred. 

If there is no error, then the value associated with the <code>responseData</code> key of the returned object
will contain the JSON response from the API.


Security Wrapper Errors
---------------------
It is possible that while making an API call, an error occurs. In this section, we will discuss 
security wrapper errors, their meanings and resolutions. The underlying APIs are "wrapped" by a security
layer that makes sure the APIs are not accessed in an unauthorized manner. We shall be discussing errors that
can be generated by this layer.

We shall not be discussing resource specific API errors.
Resource specific API errors will be discussed in the resource API description themselves.

As we see in the table below, all errors related to the security wrapper have an HTTP status code of 500, 400 or 403.

In addition to this HTTP status code, the response itself contains an error code supplied by the API 
security wrapper. This is in contrast to resource specific API errors which all have an HTTP status code of 200.

<table>
<tr>
    <td>Http Status Code</td>
    <td>Kalematie Error Code</td>
    <td>Description</td>
    <td>Scenario</td>
    <td>Resolution</td>
</tr>
<tr>
    <td>500</td>
    <td>10001</td>
    <td>Error creating token</td>
    <td>The token could not be created in the underlying data storage</td>
    <td>May be due to network issues. Try again later</td>
</tr>
<tr>
    <td>403</td>
    <td>10002</td>
    <td>Invalid access token</td>
    <td>The token could not be validated</td>
    <td>Go through the token issuing flow again to obtain a new token</td>
</tr>
<tr>
    <td>400</td>
    <td>10002</td>
    <td>Token was missing in the request</td>
    <td>Authorization header does not contain token</td>
    <td>Authorization header value must be:<br/> <code>Bearer &lt;token&gt;</code></td>
</tr>
<tr>
    <td>400</td>
    <td>10003</td>
    <td>Request needs HTTPS</td>
    <td>An attempt was made to access API using HTTP</td>
    <td>Reissue request using HTTPS</td>
</tr>
<tr>
    <td>500</td>
    <td>10004</td>
    <td>Error setting security principal</td>
    <td>We could not set the security context for your token</td>
    <td>Contact administrator</td>
</tr>
<tr>
    <td>500</td>
    <td>10005</td>
    <td>Error issuing token</td>
    <td>We could not create a token in the underlying storage</td>
    <td>Try again later. If problem persists, contact administrator</td>
</tr>
<tr>
    <td>403</td>
    <td>10006</td>
    <td>Invalid credentials</td>
    <td>We could not validate the supplied credentials</td>
    <td>Send the correct credentials and try again</td>
</tr>
<tr>
    <td>400</td>
    <td>10007</td>
    <td>Request does not contain <code>Authorization</code> header</td>
    <td>A request was made to API without <code>Authorization</code> header present</td>
    <td>Send the request with the <code>Authorization</code> header present</td>
</tr>
<tr>
    <td>403</td>
    <td>10008</td>
    <td>Could not authenticate request</td>
    <td>The request could not be authenticated via an access token</td>
    <td>Go through token issuing flow again and try again with the new token</td>
</tr>
<tr>
    <td>400</td>
    <td>10009</td>
    <td>Body missing grant_type</td>
    <td>The body of the request must be:<br/> <code>grant_type=client_credentials</code></td>
    <td>Reissue request with <code>grant_type=client_credentials</code> present in body</td>
</tr>
<tr>
    <td>400</td>
    <td>10010</td>
    <td>Body missing access token</td>
    <td>Body must contain<br/><code>access_token=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...</code></td>
    <td>Reissue request with <code>access_token</code> present in body</td>
</tr>
<tr>
    <td>400</td>
    <td>10011</td>
    <td>Base64 decoding failed</td>
    <td>Error while decoding your Base64 encoded credentials string</td>
    <td>Make sure that your Base64 encoding is correct. See <a href="http://en.wikipedia.org/wiki/Base64">Wikipedia</a></td>
</tr>
<tr>
    <td>400</td>
    <td>10012</td>
    <td>Message has incorrect number of parts</td>
    <td>Error while splitting credentials with :</td>
    <td>Make sure that you concatenate the credentials before Base64 encoding in the form <code>consumerSecret:consumerKey</code></td>
</tr>
<tr>
    <td>400</td>
    <td>10013</td>
    <td>Url decoding failed</td>
    <td>Error while url decoding consumerSecret or consumerKey</td>
    <td>Make sure that you correctly URL encode cedentials before concatenating with ':' and Base64 encoding them.</td>
</tr>
<tr>
    <td>400</td>
    <td>10014</td>
    <td>Error calling underlying resource API</td>
    <td>Authentication suceeded, but calling the underlying resource API resulted in an uncaught exception</td>
    <td>If the problem persists, contact administrator</td>
</tr>
</table>

**Example of a security wrapper error response**

    HTTP/1.1 403 Forbidden
    Cache-Control: no-cache
    Pragma: no-cache
    Content-Type: application/json; charset=utf-8
    Expires: -1
    Server: Microsoft-IIS/8.0
    X-AspNet-Version: 4.0.30319
    X-Powered-By: ASP.NET
    Date: Thu, 23 May 2013 15:13:05 GMT
    Content-Length: 123
    
    {"errorMessage":"Please authenticate by a request to /api/token before calling any API methods","errorType":1,"errorCode":10008}

Note the non 200 HTTP Status code and "errorType":1 which indicate that this is a security wrapper error and not an API error.

**Example of an API error response**

All API error responses have a HTTP status code of 200. We will show an example of just one error response that
results while trying to retrieve a list with an id that does not exist. Specific errors related to resources will
be discussed when we discuss the resource API. The error response from a resource API error (and **NOT** from the 
security wrapper layer) is shown below:
    
    HTTP/1.1 200 OK
    Cache-Control: no-cache
    Pragma: no-cache
    Content-Type: application/json; charset=utf-8
    Expires: -1
    Server: Microsoft-IIS/8.0
    X-AspNet-Version: 4.0.30319
    X-Powered-By: ASP.NET
    Date: Thu, 23 May 2013 16:09:11 GMT
    Content-Length: 90
    
    {"errorMessage":"The specified list does not exist.","errorCode":5005,"responseData":null}

One should note that the HTTP status code for this response was 200 and hence it is an resource API error specified
by the API error code in the 5000 range. A detailed discussion of 5000 range API codes will ensue when we talk 
about Resource APIs later.


An alternative for push notification
======================================
Instead of going through the hassle of implementing push notification,
you can calculate the average time quotes created and send a number with the responses
to the app client to tell them when to send requests.

# Group Token

This portion of the API pertains to obtaining a bearer token from the <b>Security Wrapper</b>. The bearer token thus
obtained is passed in the <code>Authorization</code> header in all subsequent requests to the underlying
resource APIs.

Errors that might occur due to this request :

<table>
<tr>
    <td>Http Status Code</td>
    <td>Kalematie Error Code</td>
    <td>Description</td>
    <td>Scenario</td>
    <td>Resolution</td>
</tr>
<tr>
    <td>500</td>
    <td>10001</td>
    <td>Error creating token</td>
    <td>The token could not be created in the underlying data storage</td>
    <td>May be due to network issues. Try again later</td>
</tr>
</table>

## Access token [/api/token]


### Get an access token [POST]

Get an access token based on Base64 encoded credentials (as discussed in the section above).

+ Request
    
    + Headers
            
            Athorization: Basic TTJFNU1EZGpNbVl0WldNMU5DMDBZbVJsTFRsa1kxSXRaakUzTTJabU1qWTVNVEEwOk5HVTFOemc1WTJVdFlUWXhOeTAxTURNMkxXSmlZV1l0WXpFNFkySTVaR1kyTVRjeA==
            content-length: 29
            accept-encoding: gzip
            content-type: appliaction/json

   

+ Response 200 (appliaction/json)

        {
            "errorMessage":"",
            "errorCode":0,
            "responseData": {
                "token_type": "Bearer",
                "access_token":"ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj"
            }
        }


## Token invalidation [/api/invalidate_token]

Should a bearer token become compromised or need to be invalidated for any reason, this API call can be used.
The <code>Authorization</code> header should contain the Base64 encoded credentials. The body of the request
should contain the <code>access_token</code> that needs to be invalidated.



### Invalidate an access token [POST]

+ access_token (string) - the access token that should be invalidated Which is supposed to belong to u

+ Request
    
    + Headers
        
            Authorization: Basic TTJFNU1EZGpNbVl0WldNMU5DMDBZbVJsTFRsa1kxSXRaakUzTTJabU1qWTVNVEEwOk5HVTFOemc1WTJVdFlUWXhOeTAxTURNMkxXSmlZV1l0WXpFNFkySTVaR1kyTVRjeA==
            Content-Length: 61
            Content-Type: application/x-www-form-urlencoded

    + Body
            
            access_token=ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj


+ Response 200 (application/json)

        {
            "errorMessage": "",
            "errorCode": 0,
            "responseData" : {
                "accress_token" = "ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj"
            }
            
        }
        
        
# Group Quote

+ id (number) - the quote's id.
+ text (string) - The actual quote.
+ author_id (number) - The author's ID.
+ date_published (date) - A standard date in which the quote was published.
+ rating (number) - A number between 0 and 10 that represents a quote's rating.
+ viewers (number) - The number of members who viewed the quote and rated it.

## Quotes [/api/quotes]


### Create a new quote [POST]

Create a new quote.
This action creates a quote but is not published unless it gets validated by the monitors who check for their Originality.
They will search for them in the search engines and the archive and if not found, they get published.

Errors that might take place when making this request :

<table>
<tr>
    <td>Http Status Code</td>
    <td>Kalematie Error Code</td>
    <td>Description</td>
    <td>Scenario</td>
    <td>Resolution</td>
</tr>
<tr>
    <td>200</td>
    <td>5001</td>
    <td>Incorrect body format</td>
    <td>The text for the query is missing or there isn't any text parameter</td>
    <td>Format the body correctly and resend it with another request</td>
</tr>
<tr>
    <td>200</td>
    <td>5002</td>
    <td>Body too big</td>
    <td>The number of the body exceeds the permitted limit.</td>
    <td>Provide a shorter quote</td>
    
</tr>
<tr>
    <td>200</td>
    <td>5003</td>
    <td>This quote is not original</td>
    <td>Might be a copy of someone else's quote</td>
    <td>Come up with an original quote and try later</td>
    
</tr>
    <td>200</td>
    <td>5004</td>
    <td>This quote contains forbidden content</td>
    <td>A quote that would contain political or taboo content</td>
    <td>Come up with a more respectable quote</td>
</tr>
</table>

+ text (string) - the quote

+ Request
        
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj
            Content-Type: appliaction/json
            
    + Body
            
            {
                "text": "Sometimes I feel like only google understands me."
            }


+ Response 200
    
    + Headers
            
            Location: /api/quotes/1

    + Body
    
            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": ""
            }

## Rating [/api/quotes/{quote_id}/rating]

This resource is used to rate quotes or update their rating.


+ Parameters
    + quote_id (required, number) - The id of the quote that is going to be rated
    
    

### Rate a quote [POST]

This action is used to rate a quote or update its rating. You need to provide a number between 0 and 10 
in the body to represent your rating.

User errors that might occur due to this request :

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5005</td>
        <td>Rating number not within the permitted limit</td>
        <td>giving a rating number bigger than 10 or less than 0</td>
        <td>Give a rating number between 0 and 10</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5006</td>
        <td>A member can't rate his own quote.</td>
        <td>A member rated his own quote.</td>
        <td>Don't rate your own quote.</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5007</td>
        <td>Invalid quote_id.</td>
        <td>Someone tried to rate a quote that is deleted or doesn't exist.</td>
        <td>Provide a quote_id that belongs to an existing quote</td>
    </tr>
</table>

+ rating (number, required) - A number between 0 and 10 that will represent your rating

+ Request
    
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj
            Content-type: application/json

    + Body
        
            {
                "rating": 5.5
            }

+ Response 200 (application/json)
            
            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": ""
            }   

### Retrieve a quote's rating [GET]

Error's that might take place by making this request:

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5008</td>
        <td>The quote doesn't exist so there is not rating for it.</td>
        <td>An invalid quote_id parameter given.</td>
        <td>Provide a quote_id number for an existing quote</td>
    </tr>
</table>


+ Request

    + Headers
    
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj

+ Response 200 (application/json)

            {
                "errorMessage": "",
                "errorCode":0,
                "responseData": {
                    "rating": 9.2
                }
            }
            

## Resource representing a single quote [/api/quotes/{quote_id}]

This resource represents a single quote

+ Parameters
    + quote_id (required, number) - the Id of the single quote we're talking about
    

### Update/Modify a quote [PUT]

This action is used to modify a quote.    
point : modifying a quote puts it in the line for validation and sets the rating to the default

Error's that might take place by making this request:
    
<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5007</td>
        <td>Invalid quote_id </td>
        <td>U are trying to modify a quote that doesn't exist.</td>
        <td>Retry with a valid quote_id</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5001</td>
        <td>Incorrect body format</td>
        <td>The text for the query is missing or there isn't any text parameter</td>
        <td>Format the body correctly and resend it with another request</td>
    </tr>
</table>

+ text (string) - the text for the new modified quote.
    
+ Request
    
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj
            Content-type: application/json

    + Body
    
            {
                "text": "This is the modified quote"
            }
            
+ Response 200

    + Headers
    
            Location: /api/quotes/3
            
    + Body
            
            {
                "errorMessage": "",
                "errorCode": 0,
                "responseData": ""
            }
            
### Delete a quote [DELETE]

This action is used to delete a quote.

Erro's that might take place due to this request :
    
<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5007</td>
        <td>Invalid quote_id </td>
        <td>U are trying to modify a quote that doesn't exist.</td>
        <td>Retry with a valid quote_id</td>
    </tr>
</table>

+ Response 200 (application/json)

            {
                "errorMessage": "",
                "errorCode": 0,
                "responseData": ""
            }

### Retrieve a quote [GET]

This action is used to retrive a single quote by its Id

Errors that might occur by making this action :

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5007</td>
        <td>Invalid quote_id </td>
        <td>U are trying to modify a quote that doesn't exist.</td>
        <td>Retry with a valid quote_id</td>
    </tr>
</table>
    
+ Response 200 (application/json)

            {
                "errorMessage": "",
                "errorCode": 0,
                "responseData": {
                    "id": 1,
                    "text": "Sometimes I feel like only google understands me!",
                    "author_id": 999,
                    "date_published": "2014-11-11T08:40:51.620Z",
                    "rating": 8.3,
                    "viewers": 1000000
                }
            }
            
            
## Quote Collection [/api/quotes?{sq}{idrange}&{ratingrange}&{authorid}&{authorratingrange}&{authoridrange}]

resource for operating on a collection of quotes

+ Parameters
    + idrange (optional, number range) - An Id range with the format min-max e.g 11-21 and max < 10000000000
    + authorid (optional, number) - The Id of the author who's quotes should be retrieved < 8000000000
    + authorratingrange (optional, number) - The rating of the authors who's quotes should be retrieved in the for of min-max.
    + ratingrange (optional, number) - A range range with the format min-max e.g 3.8-9  the min and max shoudl be numbers bewteen 0 and 10.
    + authoridrange (optinal, number range) - A range in the form min-max 
     + sq (required, string) - the search query

### Retrieve a quote collection [GET]

Errors that might occur by doing this action :

<table>
     <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5009</td>
        <td>Wrong idrange</td>
        <td>min bigger than max or min less than 1 or max bigger than 10000000000</td>
        <td>give a min < max and min > 0 and max < 10000000000 </td>
    </tr>
    <tr>
        <td>200</td>
        <td>5010</td>
        <td>Wrong authorid</td>
        <td>the given authorid less than 1 and bigger than 8000000000 </td>
        <td>provide an authorid < 8000000000 and >= 1</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5011</td>
        <td>Wrong authorrating</td>
        <td>authorrating parameter not in the permitted bound.</td>
        <td>ratings should be between 0 and 10 </td>
    </tr>
    <tr>
        <td>200</td>
        <td>5012</td>
        <td>Wrong daterange</td>
        <td>min date given bigger than max date or the dates don't follow the specified standard.</td>
        <td>Give a min-max date respectively and follow the specified standard date format</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5013</td>
        <td>Wrong ratingrange</td>
        <td>min bigger than max or the values not in the specified limit.</td>
        <td> Provide a respectively formatted min-max and values with in the range 0-10 </td>
    </tr>
</table>  

+ Response 200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": {
                    "quote_collection":[
                        {
                            "id": 1,
                            "text": "blah blah blah",
                            "author_id": 345,
                            "date_published": "2014-11-11T08:40:51.620Z",
                            "rating": 8.3,
                            "viewers": 3000000
                        }, {
                            
                            "id": 55,
                            "text": "bulshit",
                            "author_id": 444,
                            "date_published": "2014-11-11T08:40:51.620Z"
                            "rating": 4.5,
                            "viewers": 32434
                        }
                        
                    ]
                    
                }
            }
            
# Group Authors

Authors have the following attributes :

+ id (number) - A unique Id to represent a single author
+ firstname (string)
+ lastname (string)
+ nickname (string)
+ phonenumber (number) - the users phone number
+ password (string)
+ rating (number) - a number between 0 and 10 representing the user's rating
+ following (number) - the number of people this author is following
+ followers (number) - The number of people following this author

note : Error's related to this group of resources starts from 5050

User Registration
-----------------
Here is how it works ?
the user sends a phone number and password to the server.
the server validates the phone and the password
the server sends a verification code to the user
point : the verification code will be stored on the device to be mixed with the password when authenticating
the client then recreate a password using the verification code and the user provided password and sends them to the token specific resources to retrieve an access token.


## Authors [/api/authors]

### Add a new author [POST]

The errors related to this action are handled in the security layer.

+ Request

    + Headers
        
            
            Content-Type: application/json

    + Body
            
            {
                "firstname": "Nazar",
                "lastname": "Abdolkhanie",
                "phonenumber": 9169211845,
                "password": "secret"
                
            }
            
+ Response 200

    
## An Author [/api/authors/{author_id}]

resource for a single author.

+ Parameters
    + author_id (required, number) - the author's id


### Update an author information [PUT]

Error codes :

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5050</td>
        <td>Wrong author_id</td>
        <td>The author_id provided doesn't belong to a particular member or doesn't exist</td>
        <td>give an author_id that belongs to a valid author</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5051</td>
        <td>Incorrect body</td>
        <td>The json body is missing something or has an incorrect format</td>
        <td>Give a correct format just like in the api blueprint</td>
    </tr>
</table>

+ Request

    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj
            Content-type: application/json

    + Body
    
            {
                "firstname": "Ahmad",
                "lastname": "Fazeli"
            }

+ Response 200

            {
                "errorMessage":"",
                "errorCode": 0,
                "responseData":""
            }
            
### DELETE an author [DELETE]

Error codes :

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5050</td>
        <td>Wrong author_id</td>
        <td>The author_id provided doesn't belong to a particular member or doesn't exist</td>
        <td>give an author_id that belongs to a valid author</td>
    </tr>
</table>

+ Request

    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj

+ Response 200

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData":""
            }
            
            
### Retrieve an author's information [GET]

Error codes :

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5050</td>
        <td>Wrong author_id</td>
        <td>The author_id provided doesn't belong to a particular member or doesn't exist</td>
        <td>give an author_id that belongs to a valid author</td>
    </tr>
</table>

+ Request
    
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj

+ Response 200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": {
                
                    "firstname": "Nazar",
                    "lastname" : "Abdolkhanie",
                    "rating"   : 9.1
                    "followers" : 239,
                    "following" : 45
                }
            }

                


## Author Collection [/api/authors?{idrange}&{ratingrange}]

Use this resource to retrieve collections of authors

+ Parameters

    + idrange (optional, number range) - A range with the form min-max like 3-666
    + ratingrange (optional, number range) - A range with the form min-max where min and max are numbers between 0 and 10

### Retrive author collection [GET]
    
Error codes :

<table>
    <tr>
        <td>Http Status Code</td>
        <td>Kalematie Error Code</td>
        <td>Description</td>
        <td>Scenario</td>
        <td>Resolution</td>
    </tr>
    <tr>
        <td>200</td>
        <td>5052</td>
        <td>Invalid id range</td>
        <td>The given min is bigger than max or min and mix not in the allowed limit</td>
        <td>Provide an Id range in the form min-max respective where min is less than max and min > 0 and max < 6000000000 </td>
    </tr>
    <tr>
        <td>200</td>
        <td>5053</td>
        <td>Invalid rating range</td>
        <td>min and max rating not in the allowed bound</td>
        <td>Give a ratingrange in the form min and max where min and max are numbers between 0 and 10 </td>
    </tr>
</table>

+ Request
        
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj

+ Response 200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": {
                    "Authors" : [
                        {
                            "id" : 3000000,
                            "firstname" : "Hosam",
                            "lastname"  : "Abdolkhanie",
                            "rating"    : 5.3
                            "followers" : 453,
                            "following" : 35
                        }, {
                            "id" : 44433,
                            "fistname"  : "Ali",
                            "lastname"  : "Moradi",
                            "rating"    : 6.2
                            "followers" : 432,
                            "following" : 23
                        }
                    ]
                }
            }


## Followed authors [/api/authors/{author_id}/followed?{?limit}]

This resource referes to the authors that are followed by a user

+ Parameters
    + author_id (required, number)
    + limit    (optional, number limit) - limit the number of results as start-count
    

### Followe an author [POST]

send the id of the author you want to follow in the post body

+ Request
    
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj

    + Body
        
            {
                "followedAuthorId":455332
            }
            
+ Response  200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData":""
            }
            
            
### Retrieve the followed authors [GET]

+ Request
    
    + Headers
            
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj


+ Response 200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": {
                    "followedAuthors" : [
                        {
                            "authorId":344156,
                            "firstname": "Walter",
                            "lastname": "White",
                            "rating":   8.9,
                            "following" : 654,
                            "followers" : 221
                        }, {
                            
                            "authorId": 46457,
                            "firstname": "jessy",
                            "lastname": "unknown",
                            "rating" : 3.3
                            "following": 567,
                            "following": 455
                        }
                    ]
                }
            }
            

## A single followed author [/api/authors/{author_id}/followed/{id}]



### Retrieve a single followed author [GET]


+ Request
    
    + Headers
    
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj


+ Response 200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData" : {
                    
                    "firstname" : "Nazar",
                    "lastname"  : "Abdolkhanie",
                    "rating"    : 9.9,
                    "following" : 5,
                    "followers" : 45
                    
                }
            }
            

### Delete a followed author from the followed list [DELETE]

Use this action to delete an author from the follow list of yours

+ Request

    + Headers
        
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj
            

+ Response  200 (application/json)

            {
                "errorMessage":"",
                "errorCode":0,
                "responseData":""
            }
            
            
## Followers [/api/authors/{author_id}/followers]


### Retrieve an authors followers [GET]

+ Request
    
    + Headers
    
            Authorization: Bearer ZTkxMWJkODEtYjUwYy00MzUyLWFhYzEtODI3NWNkMjY0OGFj

+ Response  200 (application/json)


            {
                "errorMessage":"",
                "errorCode":0,
                "responseData": {
                    "followers": [
                        {
                            "author_id":435435,
                            "firstname" : "Ali",
                            "lastname"  : "valipur",
                            "rating"    :8.9,
                            "followers" : 3,
                            "following" : 34
                        }
                    ]
                }
            }
                    